baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-mr"
paginate = 5
disableFastRender = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  baseurl = "/"

[outputs]
  home = ["HTML", "JSON", "RSS"]
